<template>
    <div class="conList">
        <h2>内容列表</h2>
        <button @click="fo">加密</button>
        <Table :titles="titles" :data="users" @get-info="getInfo"></Table>
        <Table2 :titles="titles" :data="users" @get-info="getInfo" :handleRow="true">
            <template slot-scope="scope" style="text-align: center;">
                <button @click="handleRowDel(scope.rowInfo)">删除</button>
                <button @click="handleRowEdit(scope.rowInfo)">编辑</button>
            </template>
        </Table2>
    </div>
</template>
<script>
    import Table from 'components/myTab'
    import Table2 from 'components/myTable2'
    export default {
        name:'conList',
        components:{
            Table,
            Table2
        },
        data(){
            return {
                // titles:['用户','姓名','性别','邮箱'],
                titles:[
                    {
                        label:'用户',
                        key:'id'
                    },
                    {
                        label:'姓名',
                        key:'name'
                    },
                    {
                        label:'性别',
                        key:'sex'
                    },
                    {
                        label:'邮箱',
                        key:'email'
                    },
                ],
                users:[
                    {
                        id:1,
                        name:"zs",
                        sex:1,
                        email:"123@qq.com",
                    },
                    {
                        id:2,
                        name:"ls",
                        sex:1,
                        email:"312@qq.com",
                    },
                    {
                        id:3,
                        name:"ww",
                        sex:1,
                        email:"123@qq.com",
                    },
                    {
                        id:4,
                        name:"xh",
                        sex:2,
                        email:"233@qq.com",
                    },
                    {
                        id:5,
                        name:"xl",
                        sex:2,
                        email:"432@qq.com",
                    },
                    {
                        id:6,
                        name:"fa",
                        sex:1,
                        email:"1df@qq.com",
                    },
                    {
                        id:7,
                        name:"dle",
                        sex:1,
                        email:"789@qq.com",
                    },
                    {
                        id:8,
                        name:"df",
                        sex:1,
                        email:"123@qq.com",
                    },
                    {
                        id:9,
                        name:"zs",
                        sex:1,
                        email:"123@qq.com",
                    },
                    {
                        id:10,
                        name:"ls",
                        sex:1,
                        email:"312@qq.com",
                    },
                    {
                        id:11,
                        name:"ww",
                        sex:1,
                        email:"123@qq.com",
                    },
                    {
                        id:12,
                        name:"xh",
                        sex:2,
                        email:"233@qq.com",
                    },
                    {
                        id:13,
                        name:"xl",
                        sex:2,
                        email:"432@qq.com",
                    },
                    {
                        id:14,
                        name:"fa",
                        sex:1,
                        email:"1df@qq.com",
                    },
                    {
                        id:15,
                        name:"dle",
                        sex:1,
                        email:"789@qq.com",
                    },
                    {
                        id:16,
                        name:"df",
                        sex:1,
                        email:"123@qq.com",
                    },
                    {
                        id:17,
                        name:"zs",
                        sex:1,
                        email:"123@qq.com",
                    },
                    {
                        id:18,
                        name:"ls",
                        sex:1,
                        email:"312@qq.com",
                    },
                    {
                        id:19,
                        name:"ww",
                        sex:1,
                        email:"123@qq.com",
                    },
                    {
                        id:20,
                        name:"xh",
                        sex:2,
                        email:"233@qq.com",
                    }
                ]
            }
        },
        methods:{
            getInfo(data){
                console.log(data);
                console.log(typeof(data));
                // 在getInfo中进行函数处理，重新渲染表格的值
                setTimeout(()=>{
                    this.$nextTick(()=>{
                        this.users=[
                            {
                                id:21,
                                name:"xl",
                                sex:2,
                                email:"432@qq.com",
                            },
                            {
                                id:22,
                                name:"fa",
                                sex:1,
                                email:"1df@qq.com",
                            },
                            {
                                id:23,
                                name:"dle",
                                sex:1,
                                email:"789@qq.com",
                            },
                            {
                                id:24,
                                name:"df",
                                sex:1,
                                email:"123@qq.com",
                            },
                            {
                                id:25,
                                name:"zs",
                                sex:1,
                                email:"123@qq.com",
                            },
                            {
                                id:26,
                                name:"ls",
                                sex:1,
                                email:"312@qq.com",
                            },
                            {
                                id:27,
                                name:"ww",
                                sex:1,
                                email:"123@qq.com",
                            },
                            {
                                id:28,
                                name:"xh",
                                sex:2,
                                email:"233@qq.com",
                            },
                            {
                                id:29,
                                name:"xl",
                                sex:2,
                                email:"432@qq.com",
                            },
                            {
                                id:30,
                                name:"fa",
                                sex:1,
                                email:"1df@qq.com",
                            },
                            {
                                id:31,
                                name:"dle",
                                sex:1,
                                email:"789@qq.com",
                            },
                            {
                                id:32,
                                name:"df",
                                sex:1,
                                email:"123@qq.com",
                            },
                            {
                                id:33,
                                name:"zs",
                                sex:1,
                                email:"123@qq.com",
                            },
                            {
                                id:34,
                                name:"ls",
                                sex:1,
                                email:"312@qq.com",
                            },
                            {
                                id:35,
                                name:"ww",
                                sex:1,
                                email:"123@qq.com",
                            },
                            {
                                id:36,
                                name:"xh",
                                sex:2,
                                email:"233@qq.com",
                            },
                            {
                                id:37,
                                name:"xl",
                                sex:2,
                                email:"432@qq.com",
                            },
                            {
                                id:38,
                                name:"fa",
                                sex:1,
                                email:"1df@qq.com",
                            },
                            {
                                id:39,
                                name:"dle",
                                sex:1,
                                email:"789@qq.com",
                            },
                            {
                                id:40,
                                name:"df",
                                sex:1,
                                email:"123@qq.com",
                            },
                        ];
                    })
                },5000)
            },
            handleRowDel(data){
                console.log(data);
            },
            handleRowEdit(data){
                console.log(data);
            },
            fo(){
                this.$router.push({path:'/login',query:{data:this.$encrypt({name:'zs',age:20})}})
            }
        }
    }
</script>
<style lang="scss" type="text/scss" scoped>
    .conList{
        /deep/ .operation{
            background-color: pink;
            text-align: center;
        }
    }
</style>